CREATE TABLE membro(
	id_membro BIGSERIAL,
	nome_membro varchar(50) not null,
	cpf varchar(20) not null,
	rg varchar(20) not null,
	batizado varchar(5) not null,
	dt_nasc date not null,
	ministerio_id_ministerio integer not null,
	tipo varchar(10),
	sexo varchar(15),
	templo_id_templo integer,
	idade integer,
	turma integer,
	matricula_escola_biblica boolean,
	capacitacao_concluido boolean,
	matricula_lider boolean,
	rua varchar(50),
	numero integer,
	bairro varchar(30),
	cidade varchar(30),
	uf varchar(3),
	cep varchar(9),
	complemento varchar(10),
	celular varchar(15),
	fixo varchar(15),
	email varchar(30),
	whatsaap varchar(3),
	CONSTRAINT id_membro PRIMARY KEY(id_membro),
	FOREIGN KEY (ministerio_id_ministerio) REFERENCES ministerio(id_ministerio),
	FOREIGN KEY (templo_id_templo) REFERENCES templo (id_templo)
	);